{% set name = "va_am" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/va_am-{{ version }}.tar.gz
  sha256: e78c907dd8f6b7680e1108ad54107dd6c61500065dce72f8ccb6f3abfd4cb7ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - keras >=2.10.0
    - matplotlib-base >=3.8.4
    - netcdf4
    - numpy >=1.21.6
    - pandas >=2.0.3
    - python >=3.7
    - requests >=2.31.0
    - sympy >=1.10.1
    - tensorflow >=2.10.0
    - xarray >=2023.6.0
    - scipy >=1.11.4

test:
  imports:
    - va_am
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/va-am/
  summary: VA-AM method implementation
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cosminmarina
