{% set name = "va-am" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/va_am-{{ version }}.tar.gz
  sha256: d096df38169612b7c9d76a6a0eee23b9cd3b1ee70730d23bfce50a39ad6676e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - keras >=2.10.0
    - matplotlib-base >=3.5.3
    - netcdf4
    - numpy >=1.21.6
    - pandas >=1.2.3
    - python >=3.7
    - requests >=2.31.0
    - sympy >=1.10.1
    - tensorflow >=2.10.0
    - xarray >=0.20.2
    - scipy >=1.7.3

test:
  imports:
    - va_am
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/va-am/
  summary: VA-AM method implementation
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cosminmarina
