{% set name = "va_am" %}
<<<<<<< Updated upstream
{% set version = "0.0.4" %}
=======
{% set version = "0.1.4" %}
>>>>>>> Stashed changes


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/va_am-{{ version }}.tar.gz
<<<<<<< Updated upstream
  sha256: 686f88946a46e58282404a50cb3a40e914828ca601bbce46e2d6150ab778ef5e
=======
  sha256: fa4abea38c10f37c8b1acae79f58b6d92f8d66921dcf2bd64cea8cfa33187586
>>>>>>> Stashed changes

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - keras >=2.10.0
    - matplotlib-base >=3.5.3
    - netcdf4
    - numpy >=1.21.6
    - pandas >=1.2.3
    - python >=3.7
    - requests >=2.31.0
    - sympy >=1.10.1
    - tensorflow >=2.10.0
    - xarray >=0.20.2

test:
  imports:
    - va_am
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/va-am/
  summary: VA-AM method implementation
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cosminmarina
