{% set name = "va_am" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/va_am-{{ version }}.tar.gz
  sha256: c3ef4f5acbaf8b4324daf1bdedfc41962af5f0bc48ebb1c1b971610e90e31da2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - keras >=2.10.0
    - matplotlib-base >=3.8.4
    - netcdf4
    - numpy >=1.21.6
    - pandas >=2.0.3
    - python >={{ python_min }}
    - requests >=2.31.0
    - sympy >=1.10.1
    - tensorflow >=2.10.0
    - xarray >=2023.6.0
    - scipy >=1.11.4
    - seaborn >=0.13.2

test:
  imports:
    - va_am
  commands:
    - pip check
    - echo "=== DEBUG: Checking recipe directory ==="
    - ls -la /home/conda/recipe_root/
    - echo "=== DEBUG: Looking for LICENSE files ==="
    - find /home/conda/recipe_root -name "*license*" -o -name "*LICENSE*" -type f
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/va-am/
  summary: VA-AM method implementation
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cosminmarina
